language: R
sudo: false
cache: packages

before_install:
  - sudo apt-get install -y libgetdns-devel libidn2-devel libunbound-devel

addons:
  apt:
    update: true

after_success:
  - Rscript -e 'covr::codecov()'
