# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Return gdns library version
#'
#' @export
gdns_lib_version <- function() {
    .Call(`_clandnstine_gdns_lib_version`)
}

#' Test whether an object is an external pointer
#'
#' @param x object to test
#' @keywords internal
check_is_xptr <- function(s) {
    invisible(.Call(`_clandnstine_check_is_xptr`, s))
}

#' Test whether an external pointer is null
#'
#' @param x object to test
#' @keywords internal
is_null_xptr_ <- function(s) {
    .Call(`_clandnstine_is_null_xptr_`, s)
}

#' Internal version of gdns_resolver
#' @keywords internal
int_gdns_resolver <- function(resolvers) {
    .Call(`_clandnstine_int_gdns_resolver`, resolvers)
}

#' Resolve a host to an addrss
#'
#' @param gctx gdns resolver context created with [gdns_resolver()]
#' @param host to lookup
#' @export
#' @examples
#' x <- gdns_resolver()
#' gdns_get_address(x, "yahoo.com")
#' x %>% gdns_get_address("yahoo.com")
gdns_get_address <- function(gctx, host) {
    .Call(`_clandnstine_gdns_get_address`, gctx, host)
}

int_get_resolvers <- function(gctx) {
    .Call(`_clandnstine_int_get_resolvers`, gctx)
}

int_gdns_query <- function(gctx, name, rr) {
    .Call(`_clandnstine_int_gdns_query`, gctx, name, rr)
}

