# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Lookup IP Address(es) for a Given Host
#'
#' @param host host (length 1 <chr>)
#' @param resolver resolver address. defaults to Quad9; (length 1 <chr>)
#' @export
#' @examples
#' get_address("r-project.org")
#' get_address("yahoo.com", "1.1.1.1")
#' get_address("microsoft.com", "8.8.8.8")
get_address <- function(host, resolver = "9.9.9.9") {
    .Call(`_clandnstine_get_address`, host, resolver)
}

